/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    PlayerComponent: (() => {
      const tableId = new TableId("game", "PlayerComponent");
      return defineComponent(
        world,
        {
          value: RecsType.Boolean,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    SeedComponent: (() => {
      const tableId = new TableId("game", "SeedComponent");
      return defineComponent(
        world,
        {
          value: RecsType.BigInt,
          updatePeriod: RecsType.BigInt,
          startFrom: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    StageComponent: (() => {
      const tableId = new TableId("game", "StageComponent");
      return defineComponent(
        world,
        {
          value: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    ScoreComponent: (() => {
      const tableId = new TableId("game", "ScoreComponent");
      return defineComponent(
        world,
        {
          value: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    RankComponent: (() => {
      const tableId = new TableId("game", "RankComponent");
      return defineComponent(
        world,
        {
          addr: RecsType.StringArray,
          score: RecsType.NumberArray,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    GameConfigComponent: (() => {
      const tableId = new TableId("game", "GameConfigCompon");
      return defineComponent(
        world,
        {
          config1: RecsType.BigInt,
          config2: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
