/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/scene/Game.ls
 */
export class GameBase extends Laya.Scene {
    public bg: Laya.Image;
    public slot_bg: Laya.Image;
    public score_text: Laya.Text;
    public view: Laya.Image;
    public Mask: Laya.Image;
}

