/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/scene/Login.ls
 */
export class LoginBase extends Laya.Scene {
    public Start_Button: Laya.Image;
    public Rank_Button: Laya.Image;
    public Mask: Laya.Image;
}

