// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { PlayerComponent, PlayerComponentTableId } from "./tables/PlayerComponent.sol";
import { SeedComponent, SeedComponentData, SeedComponentTableId } from "./tables/SeedComponent.sol";
import { StageComponent, StageComponentTableId } from "./tables/StageComponent.sol";
import { ScoreComponent, ScoreComponentTableId } from "./tables/ScoreComponent.sol";
import { RankComponent, RankComponentData, RankComponentTableId } from "./tables/RankComponent.sol";
import { GameConfigComponent, GameConfigComponentData, GameConfigComponentTableId } from "./tables/GameConfigComponent.sol";
