// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum GameConfigType {
  SlotNum,
  ComposeNumMin,
  ComposeNumMax,
  TypeNum,
  LevelBlockInitNum,
  BorderStep,
  LevelNum,
  CardSize,
  ViewWidth,
  ViewHeight,
  AlphabetNum,
  ColorNum,
  StageNum
}
