/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/P_victory.lh
 */
export class gameResultBase extends Laya.Dialog {
    public Text: Laya.Text;
}

