/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/P_dialog.lh
 */
export class gameDialogBase extends Laya.Dialog {
    public Button: Laya.Button;
    public Text: Laya.Text;
}

